### ISSUE TITLE
Bug: empty body is not handled correctly by `res.text()`

### ISSUE THREAD

**Issue by firstdoit** [thenables/requisition#21]
On [this line](https://github.com/thenables/requisition/blob/master/lib/response.js#L165), nothing will ever happen (i.e. no `data` or `end` events will be sent) if the `content-length` of the body is 0. Apparently we can detect this because `res.readable === false` in this case. So we should check that (meaning there's no body) and return an empty string (to maintain the `text` semantics) or `null`.

If you agree, I can PR.

**Comment by jonathanong** [comment]
yep.  i think in koa or else where, we had a "hasBody()" function that checks whether there is even a body. we could do something similar

**Comment by firstdoit** [comment]
OK, great, I'll take a look at it this weekend!

**Comment by jonathanong** [comment]
- most of `StatusCodeError` should use `http-errors`. i think this library uses it. i don't mind a overridable function that "serializes" errors.
- `.thenJson()` and `.thenText()` have weird names. not sure how much value they provide when being used with async functions.
- `request.query()` - no idea why that change is necessary
- `request.sendStream()` - yes, though IMO `.send(stream)` should work automatically vs. creating a new function

**Comment by firstdoit** [comment]
* Agree about the `http-errors`
* I agree the names are terrible. The idea here is that a client API shouldn't return a "pending" request that only starts when the user calls `then`. It's meant to conform with the common practice of returning a promise, not a-thing-that-will-be-a-promise-upon-calling-then. We can discuss this further, but I think this is the weirdest part in the API right now. I'd rather have a more explicit wait to say **go** than calling `then`. What do you think?
* Our query patch basically uses `Object.keys` and doesn't apply `undefined` or empty strings.
* I agree it should be a different behaviour inside `send` - I just didn't want to patch the entire `send` - but I plan to when forking.

**Comment by firstdoit** [comment]
Ah, turns out we're going to go with https://github.com/sindresorhus/got for now!

**Comment by dazoe** [comment]
I have run into this issue as well and believe this bug should be fixed. inside text() a simple check for content-length should fix it and have it return an empty string.
