### ISSUE TITLE
Follow redirects by default

### ISSUE THREAD

**Issue by domenic** [thenables/requisition#7]
Quite surprising for a higher-level library not to do so IMO.

**Comment by jonathanong** [comment]
i swore i did... r u interested in helping? i haven't looked at this in a while, though i really should

**Comment by domenic** [comment]
Meh, maaaybe, I'm already yakshaving pretty hard on this side project though so not sure I want to start upstreaming things quite yet haha

**Comment by jonathanong** [comment]
oh i think the default is just 0. i'll bump it up later and give this module some love
